**Data Preprocessing of Student Data**

In [26]:
# importing pandas for data manipulation
import pandas as pd
# importing numpy for numerical operations
import numpy as np

**Load and Explore Dataset**

In [27]:
# Loading the dataset
df = pd.read_csv('student_data_100_preprocess.csv')

**Data Exploration**

In [28]:
# Displaying the first 5 rows to understand the dataset structure
df.head()

   Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
0    Male   NaN            1.0        65.0           Graduate         95.0
1  Female  21.0            1.0        80.0           Graduate         70.0
2    Male   NaN            3.0        60.0       Postgraduate         60.0
3    Male  21.0            2.0        60.0        High School         80.0
4    Male  20.0            5.0        80.0           Graduate          NaN

In [29]:
# Displaying the last 5 rows of the dataset
df.tail()

    Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
95  Female  18.0            6.0         NaN       Postgraduate         65.0
96  Female  20.0            6.0        95.0        High School          NaN
97  Female  20.0            3.0        80.0                NaN         75.0
98  Female  18.0            6.0        60.0                NaN         50.0
99    Male  19.0            8.0        90.0                NaN         90.0

In [30]:
# Checking number of rows and columns in the dataset
df.shape

(100, 6)

In [31]:
# Listing all column names
df.columns

Index(['Gender', 'Age', 'Hours_Studied', 'Attendance', 'Parental_Education',
       'Final_Score'],
      dtype='object')

In [32]:
# Checking data types of each column
df.dtypes

Gender                 object
Age                   float64
Hours_Studied         float64
Attendance            float64
Parental_Education     object
Final_Score           float64
dtype: object

**Identifying Coulmn Types**

In [33]:
# Selecting numerical columns (integer and float types)
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
# Selecting categorical columns (object type)
categorical_cols = df.select_dtypes(include=['object']).columns

# Printing both types of columns
print("Numerical Columns:", numerical_cols)
print("Categorical Columns:", categorical_cols)

Numerical Columns: Index(['Age', 'Hours_Studied', 'Attendance', 'Final_Score'], dtype='object')
Categorical Columns: Index(['Gender', 'Parental_Education'], dtype='object')

**Statistical Summary**

In [34]:
# Generating stastical summary for numerical columns
df.describe()

             Age  Hours_Studied  Attendance  Final_Score
count  91.000000      90.000000   92.000000    93.000000
mean   19.417582       4.366667   76.684783    74.247312
std     1.174412       2.348559   11.843234    14.632198
min    18.000000       1.000000   60.000000    50.000000
25%    18.000000       3.000000   65.000000    60.000000
50%    19.000000       4.000000   77.500000    75.000000
75%    21.000000       6.000000   85.000000    90.000000
max    21.000000       8.000000   95.000000    95.000000

**Identifying Missing Values**

In [35]:
# Checking for missing values in each column
df.isnull().sum()

Gender                 0
Age                    9
Hours_Studied         10
Attendance             8
Parental_Education    13
Final_Score            7
dtype: int64

**Handling Missing Values**

In [36]:
# Filling the missing values in numerical columns using mean
for col in numerical_cols:
  df[col].fillna(df[col].mean(), inplace=True)

/tmp/ipykernel_544/3086604992.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

In [37]:
# Filling missing values in categorical columns using mode
for col in categorical_cols:
  df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_544/383291900.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [38]:
# Verifying that no missing values remain
df.isnull().sum()

Gender                0
Age                   0
Hours_Studied         0
Attendance            0
Parental_Education    0
Final_Score           0
dtype: int64

In [39]:
# Displaying dataset information after cleaning
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Gender              100 non-null    object
 1   Age                 100 non-null    float64
 2   Hours_Studied       100 non-null    float64
 3   Attendance          100 non-null    float64
 4   Parental_Education  100 non-null    object
 5   Final_Score         100 non-null    float64
dtypes: float64(4), object(2)
memory usage: 4.8+ KB

In [40]:
# Displaying updated statistical summary
df.describe

<bound method NDFrame.describe of     Gender        Age  Hours_Studied  Attendance Parental_Education  \
0     Male  19.417582            1.0   65.000000           Graduate
1   Female  21.000000            1.0   80.000000           Graduate
2     Male  19.417582            3.0   60.000000       Postgraduate
3     Male  21.000000            2.0   60.000000        High School
4     Male  20.000000            5.0   80.000000           Graduate
..     ...        ...            ...         ...                ...
95  Female  18.000000            6.0   76.684783       Postgraduate
96  Female  20.000000            6.0   95.000000        High School
97  Female  20.000000            3.0   80.000000           Graduate
98  Female  18.000000            6.0   60.000000           Graduate
99    Male  19.000000            8.0   90.000000           Graduate

    Final_Score
0     95.000000
1     70.000000
2     60.000000
3     80.000000
4     74.247312
..          ...
95    65.000000
96    74.247312
97    75.000000
98    50.000000
99    90.000000

[100 rows x 6 columns]>

**Encoding categorical Variables**

In [41]:
# Importing LabelEncoder for comnverting categorical data to numerical
from sklearn.preprocessing import LabelEncoder

# Creating LabelEncoder object
le = LabelEncoder()

# Encoding 'Gender' column into numerical values
df['Gender'] = le.fit_transform(df['Gender'])

In [42]:
# Applying One-Hot Encoding to 'Parental_Education' column
df = pd.get_dummies(df, columns=['Parental_Education'])

In [43]:
# Checking final structure to ensure all is numerical
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Gender                           100 non-null    int64
 1   Age                              100 non-null    float64
 2   Hours_Studied                    100 non-null    float64
 3   Attendance                       100 non-null    float64
 4   Final_Score                      100 non-null    float64
 5   Parental_Education_Graduate      100 non-null    bool
 6   Parental_Education_High School   100 non-null    bool
 7   Parental_Education_Postgraduate  100 non-null    bool
dtypes: bool(3), float64(4), int64(1)
memory usage: 4.3 KB

**Preparing Data**

In [44]:
# Separating features (x) and target variable (y)
X = df.drop('Final_Score', axis=1) # All columns except Final_Score
y = df['Final_Score'] # Target variable

In [45]:
# Importing train_test_split for splitting dataset
from sklearn.model_selection import train_test_split

# Splitting data into training (80%) and testing (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

**Verifying Data Split**

In [46]:
# Printing shapes of training and testing datasets
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(80, 7) (20, 7)
(80,) (20,)